---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: dogkop
  name: dogkop
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: dogkop-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]

  # Application: cluster-wide access.
  - apiGroups: [datadog.mzizzi]
    resources: [monitors]
    verbs: [list, watch, patch]

  # Framework: cluster wide access to create/patch event resources
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: dogkop-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dogkop-role-cluster
subjects:
  - kind: ServiceAccount
    name: dogkop
    namespace: dogkop